#!/bin/bash

# Usage
function usage() {
  cat << EOS >&2
Usage: trivy docker [-h,--help] TYPE NAME [TRIVY OPTION]
 A Trivy plugin that scans the images of a docker resource.

Options:
  -h, --help    Show usage.

Examples:
  # Scan the images
  trivy docker 

EOS
  exit
}

function scan {
  trivy image $@
}

if [[ ($# -eq 0) || ($1 == "--help") || ($1 == "-h") ]]; then
  # No commands or the --help flag passed and we'll show the usage instructions
  usage
fi

DOCKER_PARAM=()
for opt in "$@"; do
  case "${opt}" in
    '--' )
      shift
      TRIVY_PARAM=( "$@" )
      break
      ;;
    * )
      if [ -n "$1" ]; then
        DOCKER_PARAM+=("$1")
      fi
      shift
      ;;
  esac
done


images=$(docker images "${DOCKER_PARAM[@]}" {{'.Repository'}}:{{'.Tag'}} | uniq)
while read -r image; do
  if [ -n "$image" ]; then
    scan "${TRIVY_PARAM[@]}" "$image"
  fi
done <<< "$images"

